services:
  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=sakila
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
  app:
    depends_on:
      - mysqlserver
    build:
      context: .
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://mysqlserver/sakila
    stdin_open: true
    volumes:
      - ./:/app

volumes:
  mysql_data:
  mysql_config:
      