services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
        - "5672:5672" #JMS Port
        - "15672:15672" #Management Port - default user:pass = guest:guest
  mysqlserver:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=sakila
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
  app:
    depends_on:
      - rabbitmq
      - mysqlserver
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://mysqlserver/sakila
      - RABBIT_HOST=rabbitmq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
    stdin_open: true
volumes:
  mysql_data:
  mysql_config:
      